format = """
$directory\
$custom\
$git_branch\
$git_status\
$git_state\
$character\

"""

[fill]
symbol = " "

[directory]
truncation_length = 1
style = "blue"
read_only = " "
home_symbol = 'home'
format = '[dir:](red)\([$path]($style)\)' 

[character]
success_symbol = "[ ✗](yellow)"
error_symbol = "[ ✗](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
format = ' \([$branch]($style)\)'
style = "green"

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = "yellow"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"


[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

